### ISSUE TITLE
Edits/Additions

### ISSUE THREAD

**Issue by benwills** [abusalimov/SublimeCImproved#14]
I made a number of changes and additions to the .tmLanguage file for my own purposes. I'm more than happy to share those changes. If you'd like them, how would you like for me to submit them to you? The new file is pretty hacked up, but i'd say 80-90% may still be the same. All changes are relevant to c. I don't know c++, so I don't know how it would affect that.

I've added regexes to more finely tune pointer identification, dereferencing, and some other common (non-official) standards for macros and the like.

It also took a bit of work to create a new theme file based on the language file, but I'm more than happy to share that, too if it makes sense to be included, even supplementally.

Thanks a ton for putting this together. It's really helped a lot.

**Comment by abusalimov** [comment]
Hi Ben,

Thanks for getting in touch! I'm glad to know that you find the project useful. And I surely would like to take a look at your improvements, of course share them!

The usual way to propose changes on GitHub is a Pull Request, please feel free to open one. If you're not familiar with that, here is an [overview](https://help.github.com/articles/using-pull-requests/). That is, first you fork a repo (I noticed, you've already done it), create a branch, and commit your changes there. After that, open a Pull Request so that I could review your changes, maybe give you some feedback, and merge the branch eventually.

There's only one more thing: since you claim that you made some (obviously) non-trivial changes, I would really appreciate if you break them into a set of atomic commits, i.e. one per logical change, instead of committing all of them at once. :+1: 

Thanks in advance!

**Comment by benwills** [comment]
Sounds great, Eldar! I'll get that done tonight. Also, thanks for the link on how to do a pull request. Your assumption was right that I've not done one. Looking forward to going through the process.

**Comment by benwills** [comment]
I just submitted the pull request.

You'd asked for multiple pull requests, but I couldn't see how to do that without making an edit, then submitting a pull request, then making another edit, and making another pull request. Is there an easier way to do it, or is that how you'd like for me to do it? If so, I can do that. Just wanted to make sure first. 

Either way, I went ahead and cleaned up the code and got it as close to your version as possible, and commented each edit I made.

As for the theme in Sublime Text, here's what I've put together if you're interested. I'll be writing a quick note in a readme here in a second.
https://github.com/benwills/cTheme

Also, another user had mentioned macros. I have some in the pull request I submitted that looks for functions that are all capital letters, numbers, and underscores. Not sure if that works, but if so, that's there.

Finally, I'm not entirely sure how Sublime Text handles the language files. I definitely got stuck a lot trying to get some things to work. I'm comfortable with regular expressions, but think I got stuck with not understanding how Sublime Text parses the file. The point of that is to say that my changes may not be good, or to certain standards. They're working for me, but if something is wrong or off with them, I'm more than happy to go back and correct some things if you can point me to specific documentation!

**Comment by abusalimov** [comment]
Thank you!

> You'd asked for multiple pull requests, but I couldn't see how to do that without making an edit, then submitting a pull request, then making another edit, and making another pull request. Is there an easier way to do it, or is that how you'd like for me to do it? If so, I can do that.

Not quite that. I asked to split the work into a set of commits, but in a single Pull Request. The way you do it is just committing to a branch (`master` in case of #17) associated with the PR, the latter will be updated accordingly.

You may wish to rollback the commits first (remove from the history, in other words):
```
git reset v1.4.0
```
This keeps your working tree, but makes it like all the changes are still to be committed.

Now you can commit them one-by-one. I recommend you to use [Git package](https://packagecontrol.io/packages/Git) for Sublime. Using it, partial commits are done in a pretty straightforward way. You just select a change (literally, select lines) and run **Git: Add selected hunk** from the command palette (<kbd>Ctrl + Shift + P</kbd>). This adds the change to a so-called stage: what is to be committed next. You may want to add several hunks to the stage if they correspond to a single logical change. If something goes wrong, there's **Git: reset (unstage)** to start from the beginning. After that use **Git: Diff staged files** to review and **Git: Commit** to create a new commit.

Check that the history has been rewritten properly, e.g. with `gitk`, and publish. Since your `master` and `origin/master` have diverged, a regular `push` will be rejected, use this: 
```
git push --force origin master
```

Few more hints and advice, if that's OK for you:

  - [Set up](https://help.github.com/articles/set-up-git/#setting-up-git) a proper email, so that your commits are attributed to your GitHub account (a real link instead of a gray octocat, like [here](https://github.com/benwills/cTheme/commit/b81f0fc596414710b2000e4f47e96d69df8bbf8c))
  - Do not add lines containing "Added by: ...", leave this job to `git blame`. And your work will be [acknowledged](https://github.com/abusalimov/SublimeCImproved/graphs/contributors) to you anyway
  - Just few links that I personally found useful for myself:
    - [Atomic commits](http://www.freshconsulting.com/atomic-commits/)
    - [Changing history](http://justinhileman.info/article/changing-history/#lesson-three-how-to-change-history)
    - [The seven rules of a great git commit message](http://chris.beams.io/posts/git-commit/#seven-rules)
    - [Git Best Practices: On sausage making](https://sethrobertson.github.io/GitBestPractices/#sausage)

Hope this helps, and doesn't bore too much!

P.S. If you don't mind, let's discuss implementation-related concerns like regexes in #17.

**Comment by benwills** [comment]
Hey Eldar - that's all fantastic.

I appreciate you taking the time to make notes on all the commits and put together all of this information on working better with git! I've got a busy few days, but will rework all of this over the weekend and should have it all submitted before Monday.

Thanks again and if you have any other information that you think would help, or preferences on how to submit the pull requests, etc, by all means let me know.

**Comment by abusalimov** [comment]
> I've got a busy few days, but will rework all of this over the weekend and should have it all submitted before Monday.

This totally makes sense. I haven't reviewed pointer dereference and dot-access logic carefully yet, I'll try to finish it by the weekend.

Thanks again for your efforts and have a great week. And don't hesitate to ask if you encounter any problems.
