### ISSUE TITLE
highlighting TODO, FIXME etc

### ISSUE THREAD

**Issue by xtotdam** [abusalimov/SublimeCImproved#27]
Hi!
Thank you for great Sublime extension!
I just wanted to share my way to highlight notes in comments in hope this can be somehow generalised. Idea was taken (actually copy-pasted ;) ) from [PythonImproved](https://github.com/MattDMo/PythonImproved), which works with [Neon Color Scheme](https://github.com/MattDMo/Neon-color-scheme)
```diff
--- .config/sublime-text-2/Packages/C Improved/old C Improved.tmLanguage
+++ .config/sublime-text-2/Packages/C Improved/edited C Improved.tmLanguage
@@ -996,6 +996,29 @@
 		<dict>
 			<key>patterns</key>
 			<array>
+				<!-- start inserting here -->
+				<!-- copy-paste from Python Improved, works with Neon Color Scheme -->
+				<dict>
+					<key>captures</key>
+					<dict>
+						<key>1</key>
+						<dict>
+							<key>name</key>
+							<string>punctuation.definition.comment.python</string>
+						</dict>
+						<key>2</key>
+						<dict>
+							<key>name</key>
+							<string>comment.line.note.notation.python</string>
+						</dict>
+					</dict>
+					<key>match</key>
+					<!-- magic there -->
+					<string>^\s*(//+)\s*(BUG|FIXME|TODO|XXX).*$\n?</string>
+					<key>name</key>
+					<string>comment.line.note.python</string>
+				</dict>
+				<!-- end inserting here -->
 				<dict>
 					<key>captures</key>
 					<dict>
```
Here is how it looks like 
![2015-11-30 12 23 07](https://cloud.githubusercontent.com/assets/5108025/11467995/43713bac-975d-11e5-84dc-c8ba1c4476fa.png)

**Comment by abusalimov** [comment]
Hi!
Thanks for the suggestion.

I've just been experimenting a bit, and here's what I've achieved so far (using the Monokai Soda color scheme):
![sublime-c-improved-task-tags](https://cloud.githubusercontent.com/assets/530396/11483740/30544808-97bb-11e5-869f-c50d01a1ba93.png)

Most likely I'll also add a background line highlighting (dark blue on your example screenshot), for schemes that support that. I like the way these lines are rendered on the minimap. :)

However, there's a minor issue with the Neon scheme, namely that it matches a too strict `comment.line.note.python` scope for task tag lines. I believe there should be something like `comment.line.note`, which doesn't limit it to the Python syntax. I guess, you could suggest them the obvious fix, if you wish. ;-)

Anyway, I'll let you know once I prepare a PR so that you could test the feature before releasing it.

**Comment by xtotdam** [comment]
This looks really nice! I didn't know this is possible on vanilla Sublime color schemes. Looking forward to your update!

**Comment by xtotdam** [comment]
Neon-color-scheme has been recently updated, exactly `comment.line.note.python` -> `comment.line.note`

**Comment by abusalimov** [comment]
Great! Thanks for letting me know.

**Comment by xtotdam** [comment]
It's a pleasure =)

**Comment by abusalimov** [comment]
Hi @xtotdam,

I ended up with more general solution involving more change than I expected: #28, #29, #30 (you can just check out the latter to try it out).
However, these require more further changes from a color scheme, so I've just proposed MattDMo/Neon-color-scheme#26 addressing my concerns. That PR also has a screenshot attached showing how it would look like after accepting all these changes.

**Comment by xtotdam** [comment]
Hi!
I had a very quick look at your latest commits to both CImproved and Neon (am uber-busy right now). Everything works just like it has to. Great work! Thank you
In my opinion colors are chosen just right :)
